USE MASTER
GO


IF NOT EXISTS (SELECT 1 FROM SYS.DATABASES WHERE NAME = 'DW_DB')
BEGIN
	CREATE DATABASE DW_DB 
END
GO 

USE DW_DB
GO 



--------------------------------------------------------
--  DDL for Table DIMENSAOFAIXAETARIA
--------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'DIMENSAOFAIXAETARIA')
BEGIN 
	CREATE TABLE DIMENSAOFAIXAETARIA 
	(
		CHAVEFAIXA  INT NOT NULL IDENTITY, 
		CHAVEINICIO INT, 
		CHAVEFIM    INT, 
		DEFAIXA     VARCHAR(20)
		
		PRIMARY KEY (CHAVEFAIXA)
	)  
	
END
GO


--------------------------------------------------------
--  DDL for Table DIMENSAOLOCALIDADE
--------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'DIMENSAOLOCALIDADE')
BEGIN 
	CREATE TABLE DIMENSAOLOCALIDADE 
	(
		CHAVELOCALIDADE INT NOT NULL IDENTITY, 
		SGESTADO VARCHAR(2), 
		NOESTADO VARCHAR(20), 
		NOREGIAO VARCHAR(20)

		PRIMARY KEY (CHAVELOCALIDADE)
	) 
END
GO 



--------------------------------------------------------
--  DDL for Table DIMENSAOCLIENTE
--------------------------------DIMENSAOCLIENTE------------------------
IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'CLIENTE')
BEGIN 
	CREATE TABLE DIMENSAOCLIENTE 
	(	
		CHAVECLIENTE       INT NOT NULL IDENTITY, 
		IDCLIENTE          INT, 
		CLIENTE            VARCHAR(50),
		ESTADO             CHAR(2), 
		SEXO               CHAR(1), 
		STATUS             VARCHAR(50), 
		CHAVEFAIXA         INT, 
		CHAVELOCALIDADE    INT, 
		DATAINICIOVALIDADE DATE NOT NULL, 
		DATAFIMVALIDADE    DATE

		PRIMARY KEY (CHAVECLIENTE)

		FOREIGN KEY (CHAVEFAIXA)      REFERENCES DIMENSAOFAIXAETARIA (CHAVEFAIXA),
		FOREIGN KEY (CHAVELOCALIDADE) REFERENCES DIMENSAOLOCALIDADE  (CHAVELOCALIDADE)
	)
END	 
GO

  




--------------------------------------------------------
--  DDL for Table DIMENSAOPRODUTO
--------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'DIMENSAOPRODUTO')
BEGIN 
	CREATE TABLE DIMENSAOPRODUTO 
	(
		CHAVEPRODUTO       INT NOT NULL IDENTITY, 
		IDPRODUTO          INT, 
		PRODUTO            VARCHAR(100), 
		CATEGORIA          VARCHAR(100), 
		DATAINICIOVALIDADE DATE NOT NULL, 
		DATAFIMVALIDADE    DATE
		
		PRIMARY KEY (CHAVEPRODUTO)
	) 
END
GO


--------------------------------------------------------
--  DDL for Table DIMENSAOTEMPO
--------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'DIMENSAOTEMPO')
BEGIN
	CREATE TABLE DIMENSAOTEMPO 
	(
		CHAVETEMPO INT NOT NULL IDENTITY, 
		DATA       DATE, 
		DIA        INT, 
		MES        INT, 
		ANO        INT, 
		DIASEMANA  INT, 
		TRIMESTRE  INT

		PRIMARY KEY (CHAVETEMPO)
	) 
END
GO
ALTER TABLE DIMENSAOTEMPO 
ADD NO_MES VARCHAR(15) NULL, SG_MES VARCHAR(3) NULL, DIA_SEMANA VARCHAR(15) NULL, SG_SEMANA VARCHAR(3) NULL




--------------------------------------------------------
--  DDL for Table DIMENSAOVENDEDOR
--------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'DIMENSAOVENDEDOR')
BEGIN 
	CREATE TABLE DIMENSAOVENDEDOR 
	(
		CHAVEVENDEDOR      INT  NOT NULL IDENTITY, 
		IDVENDEDOR         INT, 
		NOME               VARCHAR(50), 
		DATAINICIOVALIDADE DATE NOT NULL, 
		DATAFIMVALIDADE    DATE

		PRIMARY KEY (CHAVEVENDEDOR)
	)
END
GO 
 
--------------------------------------------------------
--  DDL for Table FATOVENDAS
--------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'FATOVENDAS')
BEGIN
	CREATE TABLE FATOVENDAS 
	(	
		CHAVEVENDAS     INT NOT NULL IDENTITY, 
		CHAVEVENDEDOR   INT, 
		CHAVECLIENTE    INT, 
		CHAVELOCALIDADE INT, 
		CHAVEFAIXA      INT, 
		CHAVEPRODUTO    INT, 
		CHAVETEMPO      INT, 
		QUANTIDADE      INT, 
		VALORUNITARIO   DECIMAL(10,2), 
		VALORTOTAL	    DECIMAL(10,2), 
		VALORDESCONTO   DECIMAL(10,2), 
		VALORLIQUIDO    DECIMAL(10,2)

		PRIMARY KEY (CHAVEVENDAS)

		FOREIGN KEY (CHAVELOCALIDADE) REFERENCES DIMENSAOLOCALIDADE  (CHAVELOCALIDADE),
		FOREIGN KEY (CHAVETEMPO)      REFERENCES DIMENSAOTEMPO       (CHAVETEMPO),
		FOREIGN KEY (CHAVEVENDEDOR)   REFERENCES DIMENSAOVENDEDOR    (CHAVEVENDEDOR),
		FOREIGN KEY (CHAVEPRODUTO)    REFERENCES DIMENSAOPRODUTO     (CHAVEPRODUTO),
		FOREIGN KEY (CHAVECLIENTE)    REFERENCES DIMENSAOCLIENTE     (CHAVECLIENTE),
		FOREIGN KEY (CHAVEFAIXA)      REFERENCES DIMENSAOFAIXAETARIA (CHAVEFAIXA)
	)  
END
GO


--------------------------------------------------------
--  DDL for Table FATOVENDASMES
--------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'FATOVENDASMES')
BEGIN 
	CREATE TABLE FATOVENDASMES 
	(	
		CHAVEVENDAS     INT NOT NULL IDENTITY, 
		CHAVEVENDEDOR   INT, 
		CHAVELOCALIDADE INT, 
		CHAVEFAIXA      INT, 
		CHAVEPRODUTO    INT, 
		CHAVETEMPO      INT, 
		QUANTIDADE      INT, 
		VALORTOTAL      DECIMAL(10,2), 
		VALORDESCONTO   DECIMAL(10,2), 
		VALORLIQUIDO    DECIMAL(10,2)

		PRIMARY KEY (CHAVEVENDAS)
	
		FOREIGN KEY (CHAVETEMPO)      REFERENCES DIMENSAOTEMPO       (CHAVETEMPO),
		FOREIGN KEY (CHAVELOCALIDADE) REFERENCES DIMENSAOLOCALIDADE  (CHAVELOCALIDADE),
		FOREIGN KEY (CHAVEFAIXA)      REFERENCES DIMENSAOFAIXAETARIA (CHAVEFAIXA), 
		FOREIGN KEY (CHAVEVENDEDOR)   REFERENCES DIMENSAOVENDEDOR    (CHAVEVENDEDOR),
		FOREIGN KEY (CHAVEPRODUTO)    REFERENCES DIMENSAOPRODUTO     (CHAVEPRODUTO)
	)  
	 
END
GO


--------------------------------------------------------
--  DDL for Table FATOVENDASTRIMESTRE
--------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'FATOVENDASTRIMESTRE')
BEGIN
	CREATE TABLE FATOVENDASTRIMESTRE 
	(	
		CHAVEVENDAS     INT NOT NULL IDENTITY, 
		CHAVEVENDEDOR   INT, 
		CHAVELOCALIDADE INT, 
		CHAVEFAIXA      INT, 
		CHAVEPRODUTO    INT, 
		CHAVETEMPO      INT, 
		QUANTIDADE      INT, 
		VALORTOTAL      DECIMAL(10,2), 
		VALORDESCONTO   DECIMAL(10,2), 
		VALORLIQUIDO    DECIMAL(10,2)

		PRIMARY KEY (CHAVEVENDAS)

		FOREIGN KEY (CHAVETEMPO)      REFERENCES DIMENSAOTEMPO       (CHAVETEMPO),
		FOREIGN KEY (CHAVEFAIXA)      REFERENCES DIMENSAOFAIXAETARIA (CHAVEFAIXA),
		FOREIGN KEY (CHAVEPRODUTO)    REFERENCES DIMENSAOPRODUTO     (CHAVEPRODUTO), 
		FOREIGN KEY (CHAVEVENDEDOR)   REFERENCES DIMENSAOVENDEDOR    (CHAVEVENDEDOR),
		FOREIGN KEY (CHAVELOCALIDADE) REFERENCES DIMENSAOLOCALIDADE  (CHAVELOCALIDADE)
	) 
END
GO


--------------------------------------------------------
--  DDL for Table ODSVENDAS
--------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'ODSVENDAS')
BEGIN 
	CREATE TABLE ODSVENDAS 
	(
		CHAVEVENDAS   INT NOT NULL IDENTITY, 
		CHAVEVENDEDOR INT, 
		CHAVECLIENTE  INT, 
		CHAVEPRODUTO  INT, 
		CHAVETEMPO    INT, 
		QUANTIDADE    INT, 
		VALORUNITARIO DECIMAL(10,2), 
		VALORTOTAL    DECIMAL(10,2), 
		VALORDESCONTO DECIMAL(10,2)

		PRIMARY KEY (CHAVEVENDAS)
	
		FOREIGN KEY (CHAVECLIENTE)  REFERENCES DIMENSAOCLIENTE  (CHAVECLIENTE),
		FOREIGN KEY (CHAVEPRODUTO)  REFERENCES DIMENSAOPRODUTO  (CHAVEPRODUTO), 
		FOREIGN KEY (CHAVETEMPO)    REFERENCES DIMENSAOTEMPO    (CHAVETEMPO),
		FOREIGN KEY (CHAVEVENDEDOR) REFERENCES DIMENSAOVENDEDOR (CHAVEVENDEDOR)
	)
	  
END
