--------------------------------------------------------
--  File created - Thursday-May-16-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DIMENSAOCLIENTE
--------------------------------------------------------

  CREATE TABLE "EDW5"."DIMENSAOCLIENTE" 
   (	"CHAVECLIENTE" NUMBER(10,0), 
	"IDCLIENTE" NUMBER(10,0), 
	"CLIENTE" VARCHAR2(50 BYTE), 
	"SEXO" CHAR(1 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"CHAVEFAIXA" NUMBER(10,0), 
	"CHAVELOCALIDADE" NUMBER(10,0), 
	"DATAINICIOVALIDADE" DATE, 
	"DATAFIMVALIDADE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DIMENSAOFAIXAETARIA
--------------------------------------------------------

  CREATE TABLE "EDW5"."DIMENSAOFAIXAETARIA" 
   (	"CHAVEFAIXA" NUMBER(10,0), 
	"CHAVEINICIO" NUMBER(10,0), 
	"CHAVEFIM" NUMBER(10,0), 
	"DEFAIXA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DIMENSAOLOCALIDADE
--------------------------------------------------------

  CREATE TABLE "EDW5"."DIMENSAOLOCALIDADE" 
   (	"CHAVELOCALIDADE" NUMBER(10,0), 
	"SGESTADO" VARCHAR2(2 BYTE), 
	"NOESTADO" VARCHAR2(20 BYTE), 
	"NOREGIAO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DIMENSAOPRODUTO
--------------------------------------------------------

  CREATE TABLE "EDW5"."DIMENSAOPRODUTO" 
   (	"CHAVEPRODUTO" NUMBER(10,0), 
	"IDPRODUTO" NUMBER(10,0), 
	"PRODUTO" VARCHAR2(100 BYTE), 
	"CATEGORIA" VARCHAR2(100 BYTE), 
	"DATAINICIOVALIDADE" DATE, 
	"DATAFIMVALIDADE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DIMENSAOTEMPO
--------------------------------------------------------

  CREATE TABLE "EDW5"."DIMENSAOTEMPO" 
   (	"CHAVETEMPO" NUMBER(10,0), 
	"DATA" DATE, 
	"DIA" NUMBER(10,0), 
	"MES" NUMBER(10,0), 
	"ANO" NUMBER(10,0), 
	"DIASEMANA" NUMBER(10,0), 
	"TRIMESTRE" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DIMENSAOVENDEDOR
--------------------------------------------------------

  CREATE TABLE "EDW5"."DIMENSAOVENDEDOR" 
   (	"CHAVEVENDEDOR" NUMBER(10,0), 
	"IDVENDEDOR" NUMBER(10,0), 
	"NOME" VARCHAR2(50 BYTE), 
	"DATAINICIOVALIDADE" DATE, 
	"DATAFIMVALIDADE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FATOVENDAS
--------------------------------------------------------

  CREATE TABLE "EDW5"."FATOVENDAS" 
   (	"CHAVEVENDAS" NUMBER(10,0), 
	"CHAVEVENDEDOR" NUMBER(10,0), 
	"CHAVECLIENTE" NUMBER(10,0), 
	"CHAVELOCALIDADE" NUMBER(10,0), 
	"CHAVEFAIXA" NUMBER(10,0), 
	"CHAVEPRODUTO" NUMBER(10,0), 
	"CHAVETEMPO" NUMBER(10,0), 
	"QUANTIDADE" NUMBER(10,0), 
	"VALORUNITARIO" NUMBER(10,2), 
	"VALORTOTAL" NUMBER(10,2), 
	"VALORDESCONTO" NUMBER(10,2), 
	"VALORLIQUIDO" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FATOVENDASMES
--------------------------------------------------------

  CREATE TABLE "EDW5"."FATOVENDASMES" 
   (	"CHAVEVENDAS" NUMBER(10,0), 
	"CHAVEVENDEDOR" NUMBER(10,0), 
	"CHAVELOCALIDADE" NUMBER(10,0), 
	"CHAVEFAIXA" NUMBER(10,0), 
	"CHAVEPRODUTO" NUMBER(10,0), 
	"CHAVETEMPO" NUMBER(10,0), 
	"QUANTIDADE" NUMBER(10,0), 
	"VALORTOTAL" NUMBER(10,2), 
	"VALORDESCONTO" NUMBER(10,2), 
	"VALORLIQUIDO" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FATOVENDASTRIMESTRE
--------------------------------------------------------

  CREATE TABLE "EDW5"."FATOVENDASTRIMESTRE" 
   (	"CHAVEVENDAS" NUMBER(10,0), 
	"CHAVEVENDEDOR" NUMBER(10,0), 
	"CHAVELOCALIDADE" NUMBER(10,0), 
	"CHAVEFAIXA" NUMBER(10,0), 
	"CHAVEPRODUTO" NUMBER(10,0), 
	"CHAVETEMPO" NUMBER(10,0), 
	"QUANTIDADE" NUMBER(10,0), 
	"VALORTOTAL" NUMBER(10,2), 
	"VALORDESCONTO" NUMBER(10,2), 
	"VALORLIQUIDO" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ODSVENDAS
--------------------------------------------------------

  CREATE TABLE "EDW5"."ODSVENDAS" 
   (	"CHAVEVENDAS" NUMBER(10,0), 
	"CHAVEVENDEDOR" NUMBER(10,0), 
	"CHAVECLIENTE" NUMBER(10,0), 
	"CHAVEPRODUTO" NUMBER(10,0), 
	"CHAVETEMPO" NUMBER(10,0), 
	"QUANTIDADE" NUMBER(10,0), 
	"VALORUNITARIO" NUMBER(10,2), 
	"VALORTOTAL" NUMBER(10,2), 
	"VALORDESCONTO" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into EDW5.DIMENSAOCLIENTE
SET DEFINE OFF;
REM INSERTING into EDW5.DIMENSAOFAIXAETARIA
SET DEFINE OFF;
REM INSERTING into EDW5.DIMENSAOLOCALIDADE
SET DEFINE OFF;
REM INSERTING into EDW5.DIMENSAOPRODUTO
SET DEFINE OFF;
REM INSERTING into EDW5.DIMENSAOTEMPO
SET DEFINE OFF;
REM INSERTING into EDW5.DIMENSAOVENDEDOR
SET DEFINE OFF;
REM INSERTING into EDW5.FATOVENDAS
SET DEFINE OFF;
REM INSERTING into EDW5.FATOVENDASMES
SET DEFINE OFF;
REM INSERTING into EDW5.FATOVENDASTRIMESTRE
SET DEFINE OFF;
REM INSERTING into EDW5.ODSVENDAS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index NEWDIMENSAOCLIENTE_PKEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDW5"."NEWDIMENSAOCLIENTE_PKEY" ON "EDW5"."DIMENSAOCLIENTE" ("CHAVECLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DIMENSAOFAIXAETARIA_PKEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDW5"."DIMENSAOFAIXAETARIA_PKEY" ON "EDW5"."DIMENSAOFAIXAETARIA" ("CHAVEFAIXA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DIMENSAOLOCALIDADE_PKEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDW5"."DIMENSAOLOCALIDADE_PKEY" ON "EDW5"."DIMENSAOLOCALIDADE" ("CHAVELOCALIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NEWDIMENSAOPRODUTO_PKEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDW5"."NEWDIMENSAOPRODUTO_PKEY" ON "EDW5"."DIMENSAOPRODUTO" ("CHAVEPRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DIMENSAOTEMPO_PKEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDW5"."DIMENSAOTEMPO_PKEY" ON "EDW5"."DIMENSAOTEMPO" ("CHAVETEMPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DIMENSAOVENDEDOR_PKEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDW5"."DIMENSAOVENDEDOR_PKEY" ON "EDW5"."DIMENSAOVENDEDOR" ("CHAVEVENDEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OUYQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDW5"."OUYQ" ON "EDW5"."FATOVENDAS" ("CHAVEVENDAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index YRCQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDW5"."YRCQ" ON "EDW5"."FATOVENDASMES" ("CHAVEVENDAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ASD
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDW5"."ASD" ON "EDW5"."FATOVENDASTRIMESTRE" ("CHAVEVENDAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FATOVENDAS_PKEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDW5"."FATOVENDAS_PKEY" ON "EDW5"."ODSVENDAS" ("CHAVEVENDAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DIMENSAOCLIENTE
--------------------------------------------------------

  ALTER TABLE "EDW5"."DIMENSAOCLIENTE" MODIFY ("DATAINICIOVALIDADE" NOT NULL ENABLE);
  ALTER TABLE "EDW5"."DIMENSAOCLIENTE" ADD CONSTRAINT "NEWDIMENSAOCLIENTE_PKEY" PRIMARY KEY ("CHAVECLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EDW5"."DIMENSAOCLIENTE" MODIFY ("CHAVECLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DIMENSAOFAIXAETARIA
--------------------------------------------------------

  ALTER TABLE "EDW5"."DIMENSAOFAIXAETARIA" MODIFY ("CHAVEFAIXA" NOT NULL ENABLE);
  ALTER TABLE "EDW5"."DIMENSAOFAIXAETARIA" ADD CONSTRAINT "DIMENSAOFAIXAETARIA_PKEY" PRIMARY KEY ("CHAVEFAIXA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DIMENSAOLOCALIDADE
--------------------------------------------------------

  ALTER TABLE "EDW5"."DIMENSAOLOCALIDADE" MODIFY ("CHAVELOCALIDADE" NOT NULL ENABLE);
  ALTER TABLE "EDW5"."DIMENSAOLOCALIDADE" ADD CONSTRAINT "DIMENSAOLOCALIDADE_PKEY" PRIMARY KEY ("CHAVELOCALIDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DIMENSAOPRODUTO
--------------------------------------------------------

  ALTER TABLE "EDW5"."DIMENSAOPRODUTO" MODIFY ("CHAVEPRODUTO" NOT NULL ENABLE);
  ALTER TABLE "EDW5"."DIMENSAOPRODUTO" MODIFY ("DATAINICIOVALIDADE" NOT NULL ENABLE);
  ALTER TABLE "EDW5"."DIMENSAOPRODUTO" ADD CONSTRAINT "NEWDIMENSAOPRODUTO_PKEY" PRIMARY KEY ("CHAVEPRODUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DIMENSAOTEMPO
--------------------------------------------------------

  ALTER TABLE "EDW5"."DIMENSAOTEMPO" MODIFY ("CHAVETEMPO" NOT NULL ENABLE);
  ALTER TABLE "EDW5"."DIMENSAOTEMPO" ADD CONSTRAINT "DIMENSAOTEMPO_PKEY" PRIMARY KEY ("CHAVETEMPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DIMENSAOVENDEDOR
--------------------------------------------------------

  ALTER TABLE "EDW5"."DIMENSAOVENDEDOR" MODIFY ("CHAVEVENDEDOR" NOT NULL ENABLE);
  ALTER TABLE "EDW5"."DIMENSAOVENDEDOR" MODIFY ("DATAINICIOVALIDADE" NOT NULL ENABLE);
  ALTER TABLE "EDW5"."DIMENSAOVENDEDOR" ADD CONSTRAINT "DIMENSAOVENDEDOR_PKEY" PRIMARY KEY ("CHAVEVENDEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FATOVENDAS
--------------------------------------------------------

  ALTER TABLE "EDW5"."FATOVENDAS" MODIFY ("CHAVEVENDAS" NOT NULL ENABLE);
  ALTER TABLE "EDW5"."FATOVENDAS" ADD CONSTRAINT "OUYQ" PRIMARY KEY ("CHAVEVENDAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FATOVENDASMES
--------------------------------------------------------

  ALTER TABLE "EDW5"."FATOVENDASMES" MODIFY ("CHAVEVENDAS" NOT NULL ENABLE);
  ALTER TABLE "EDW5"."FATOVENDASMES" ADD CONSTRAINT "YRCQ" PRIMARY KEY ("CHAVEVENDAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FATOVENDASTRIMESTRE
--------------------------------------------------------

  ALTER TABLE "EDW5"."FATOVENDASTRIMESTRE" MODIFY ("CHAVEVENDAS" NOT NULL ENABLE);
  ALTER TABLE "EDW5"."FATOVENDASTRIMESTRE" ADD CONSTRAINT "ASD" PRIMARY KEY ("CHAVEVENDAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ODSVENDAS
--------------------------------------------------------

  ALTER TABLE "EDW5"."ODSVENDAS" MODIFY ("CHAVEVENDAS" NOT NULL ENABLE);
  ALTER TABLE "EDW5"."ODSVENDAS" ADD CONSTRAINT "FATOVENDAS_PKEY" PRIMARY KEY ("CHAVEVENDAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIMENSAOCLIENTE
--------------------------------------------------------

  ALTER TABLE "EDW5"."DIMENSAOCLIENTE" ADD CONSTRAINT "CHAVEFAIXA_FKEY" FOREIGN KEY ("CHAVEFAIXA")
	  REFERENCES "EDW5"."DIMENSAOFAIXAETARIA" ("CHAVEFAIXA") ENABLE;
  ALTER TABLE "EDW5"."DIMENSAOCLIENTE" ADD CONSTRAINT "CHAVELOCALIDADE_FKEY" FOREIGN KEY ("CHAVELOCALIDADE")
	  REFERENCES "EDW5"."DIMENSAOLOCALIDADE" ("CHAVELOCALIDADE") ENABLE;





--------------------------------------------------------
--  Ref Constraints for Table FATOVENDAS
--------------------------------------------------------

  ALTER TABLE "EDW5"."FATOVENDAS" ADD CONSTRAINT "IYGWG" FOREIGN KEY ("CHAVELOCALIDADE")
	  REFERENCES "EDW5"."DIMENSAOLOCALIDADE" ("CHAVELOCALIDADE") ENABLE;
  ALTER TABLE "EDW5"."FATOVENDAS" ADD CONSTRAINT "NNVV" FOREIGN KEY ("CHAVETEMPO")
	  REFERENCES "EDW5"."DIMENSAOTEMPO" ("CHAVETEMPO") ENABLE;
  ALTER TABLE "EDW5"."FATOVENDAS" ADD CONSTRAINT "OIUHS" FOREIGN KEY ("CHAVEVENDEDOR")
	  REFERENCES "EDW5"."DIMENSAOVENDEDOR" ("CHAVEVENDEDOR") ENABLE;
  ALTER TABLE "EDW5"."FATOVENDAS" ADD CONSTRAINT "VBJAH" FOREIGN KEY ("CHAVEPRODUTO")
	  REFERENCES "EDW5"."DIMENSAOPRODUTO" ("CHAVEPRODUTO") ENABLE;
  ALTER TABLE "EDW5"."FATOVENDAS" ADD CONSTRAINT "WYHFSS" FOREIGN KEY ("CHAVECLIENTE")
	  REFERENCES "EDW5"."DIMENSAOCLIENTE" ("CHAVECLIENTE") ENABLE;
  ALTER TABLE "EDW5"."FATOVENDAS" ADD CONSTRAINT "ZALJH" FOREIGN KEY ("CHAVEFAIXA")
	  REFERENCES "EDW5"."DIMENSAOFAIXAETARIA" ("CHAVEFAIXA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FATOVENDASMES
--------------------------------------------------------

  ALTER TABLE "EDW5"."FATOVENDASMES" ADD CONSTRAINT "CZXCSDD" FOREIGN KEY ("CHAVETEMPO")
	  REFERENCES "EDW5"."DIMENSAOTEMPO" ("CHAVETEMPO") ENABLE;
  ALTER TABLE "EDW5"."FATOVENDASMES" ADD CONSTRAINT "EQWEF" FOREIGN KEY ("CHAVELOCALIDADE")
	  REFERENCES "EDW5"."DIMENSAOLOCALIDADE" ("CHAVELOCALIDADE") ENABLE;
  ALTER TABLE "EDW5"."FATOVENDASMES" ADD CONSTRAINT "FDSDWR" FOREIGN KEY ("CHAVEFAIXA")
	  REFERENCES "EDW5"."DIMENSAOFAIXAETARIA" ("CHAVEFAIXA") ENABLE;
  ALTER TABLE "EDW5"."FATOVENDASMES" ADD CONSTRAINT "QWESDXX" FOREIGN KEY ("CHAVEVENDEDOR")
	  REFERENCES "EDW5"."DIMENSAOVENDEDOR" ("CHAVEVENDEDOR") ENABLE;
  ALTER TABLE "EDW5"."FATOVENDASMES" ADD CONSTRAINT "XCAEEQWE" FOREIGN KEY ("CHAVEPRODUTO")
	  REFERENCES "EDW5"."DIMENSAOPRODUTO" ("CHAVEPRODUTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FATOVENDASTRIMESTRE
--------------------------------------------------------

  ALTER TABLE "EDW5"."FATOVENDASTRIMESTRE" ADD CONSTRAINT "DQWSD" FOREIGN KEY ("CHAVETEMPO")
	  REFERENCES "EDW5"."DIMENSAOTEMPO" ("CHAVETEMPO") ENABLE;
  ALTER TABLE "EDW5"."FATOVENDASTRIMESTRE" ADD CONSTRAINT "DSA" FOREIGN KEY ("CHAVEFAIXA")
	  REFERENCES "EDW5"."DIMENSAOFAIXAETARIA" ("CHAVEFAIXA") ENABLE;
  ALTER TABLE "EDW5"."FATOVENDASTRIMESTRE" ADD CONSTRAINT "EWQWW" FOREIGN KEY ("CHAVEPRODUTO")
	  REFERENCES "EDW5"."DIMENSAOPRODUTO" ("CHAVEPRODUTO") ENABLE;
  ALTER TABLE "EDW5"."FATOVENDASTRIMESTRE" ADD CONSTRAINT "WESSSDA" FOREIGN KEY ("CHAVEVENDEDOR")
	  REFERENCES "EDW5"."DIMENSAOVENDEDOR" ("CHAVEVENDEDOR") ENABLE;
  ALTER TABLE "EDW5"."FATOVENDASTRIMESTRE" ADD CONSTRAINT "WQEWQ" FOREIGN KEY ("CHAVELOCALIDADE")
	  REFERENCES "EDW5"."DIMENSAOLOCALIDADE" ("CHAVELOCALIDADE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ODSVENDAS
--------------------------------------------------------

  ALTER TABLE "EDW5"."ODSVENDAS" ADD CONSTRAINT "FATOVENDAS_CHAVECLIENTE_FKEY" FOREIGN KEY ("CHAVECLIENTE")
	  REFERENCES "EDW5"."DIMENSAOCLIENTE" ("CHAVECLIENTE") ENABLE;
  ALTER TABLE "EDW5"."ODSVENDAS" ADD CONSTRAINT "FATOVENDAS_CHAVEPRODUTO_FKEY" FOREIGN KEY ("CHAVEPRODUTO")
	  REFERENCES "EDW5"."DIMENSAOPRODUTO" ("CHAVEPRODUTO") ENABLE;
  ALTER TABLE "EDW5"."ODSVENDAS" ADD CONSTRAINT "FATOVENDAS_CHAVETEMPO_FKEY" FOREIGN KEY ("CHAVETEMPO")
	  REFERENCES "EDW5"."DIMENSAOTEMPO" ("CHAVETEMPO") ENABLE;
  ALTER TABLE "EDW5"."ODSVENDAS" ADD CONSTRAINT "FATOVENDAS_CHAVEVENDEDOR_FKEY" FOREIGN KEY ("CHAVEVENDEDOR")
	  REFERENCES "EDW5"."DIMENSAOVENDEDOR" ("CHAVEVENDEDOR") ENABLE;
